### ISSUE TITLE
safeArray.ToValueArray undefined

### ISSUE THREAD

**Issue by rokett** [StackExchange/wmi#29]
Hi,

I'm getting the following error when trying to compile an application using this package.

`vendor\github.com\StackExchange\wmi\wmi.go:377: safeArray.ToValueArray undefined (type *ole.SafeArrayConversion has no field or method ToValueArray)`

I've used this package in the past and the same message hasn't appeared previously.

For reference I'm using Glide to import dependencies, and am using the following versions of this package and go-ole.

- stackexchange/wmi : commit `ea383cf3ba6ec950874b8486cd72356d007c768f`
- go-ole : 1.2.0

Has anyone come across this issue before?

thanks.

**Comment by rokett** [comment]
I'm not sure what the problem was but I noticed Glide was having issues pulling in dependent packages, so I switched to govendor and it all seems to be working now.

**Comment by SilverCory** [comment]
I'm getting this with godep

**Comment by SilverCory** [comment]
Caused by go-ole tag v1.2.0 not containing ToValueArray in safearrayconversion.go. This is the correct behaviour of Glide and GoDep.

https://github.com/go-ole/go-ole/blob/v1.2.0/safearrayconversion.go
![Screenshot](https://i.imgur.com/H0MeWQ6.png)

Possible solution; in your package manager's config to use master.

**Comment by xphyr** [comment]
I am running into the same issues with "dep".  It almost seems like go-ole needs to be tagged with a v1.3 version that has the ToValueArray method.  In the mean time, I am trying to figure out how to override godep to pull the proper version of go-ole.  Any chance someone can look at this again?

**Comment by SilverCory** [comment]
@xphyr I've found this to work. ```[[override]]
  name = "github.com/go-ole/go-ole"
  branch = "master"```
