### ISSUE TITLE
Tag a 1.0.0 release please

### ISSUE THREAD

**Issue by jeffallen** [StackExchange/wmi#39]
It seems like this package is pretty stable. It would be helpful if you could tag a 1.0.0 release with "git tag 1.0.0 && git push --tags" so that if you want to make breaking API changes later, my dep will stay locked on 1.0.x. Thanks.

**Comment by tlimoncelli** [comment]
Is there anything we wouldn't do for an old LISA pal? :-)

All done.


```
$ git tag 1.0.0 && git push --tags
Total 0 (delta 0), reused 0 (delta 0)
To github.com:StackExchange/wmi.git
 * [new tag]         1.0.0 -> 1.0.0
```
