### ISSUE TITLE
should be `runtime.UnlockOSThread()`

### ISSUE THREAD

**Issue by flowchartsman** [StackExchange/wmi#43]
This appears to be a typo: https://github.com/StackExchange/wmi/blob/cdffdb33acae0e14efff2628f9bae377b597840e/swbemservices.go#L76-L80

**Comment by captncraig** [comment]
That's... embarrassing. 

If that alone accounts for the unexplained memory leaks we've seen....

I don't want to know enough to look at history on it. Thanks for the spot.

**Comment by captncraig** [comment]
Fixed in b12b22c5341f0c26d88c4d66176330500e84db68
