### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by shawnps-sigsci** [StackExchange/wmi#49]
Hi, thank you for making and maintaining this library.

Is there any way you could tag a new release?

I'm particularly concerned about this commit not being in the latest release, but maybe I'm misunderstanding it:

https://github.com/StackExchange/wmi/commit/b12b22c5341f0c26d88c4d66176330500e84db68

I like using semantic versions where possible so I'd really appreciate it.

Thank you!

**Comment by shawnps-sigsci** [comment]
Hello, any feedback on this request?

**Comment by carlpett** [comment]
This is on our wishlist as well.
@captncraig you seem to be the last active maintainer, do you have time to create a new tag? Preferrably adhering to Go module requirements, ie prefixed with a v, so something like `v1.1.0`.

**Comment by captncraig** [comment]
Tagged 1.1.0
