### ISSUE TITLE
Add support for string arrays

### ISSUE THREAD

**Issue by gbrayut** [StackExchange/wmi#5]
The IP address in Win32_NetworkAdapterConfiguration returned as a string array

See http://msdn.microsoft.com/en-us/library/aa394217(v=vs.85).aspx

**Comment by Durgababu** [comment]
Hi, 

what is the update on this issue? still it is not supporting string arrays.

**Comment by Durgababu** [comment]
Add support for string arrays #5

how can we address this issue?

wmi: cannot load field "ChassisTypes" into a "[]string": unsupported type (<nil>)


please give me the fix for array type of values.

**Comment by graf0** [comment]
Just tested  gesquive patch - working wonderfully :+1:
