### ISSUE TITLE
Can you do a new "release" for v1.2.1

### ISSUE THREAD

**Issue by lespea** [StackExchange/wmi#62]
https://github.com/shirou/gopsutil/pull/1099

I that when the v1.2.0 tag briefly was pointing at the wrong commit, some people may have cached that and it's now causing issues.  In theory if you just add a new tag for v1.2.1 then theoretically that will fix the problem once packages reference that version?

**Comment by annybs** [comment]
Just adding my +1 and further explanation of the issue here: https://github.com/shirou/gopsutil/pull/1099#issuecomment-882371341

**Comment by xuyang2** [comment]
found a workaround:
add this to your module's `go.mod`:
```

replace (
	github.com/StackExchange/wmi v1.2.0 => github.com/StackExchange/wmi v1.2.1-0.20210723131906-441642c16659
)
```

**Comment by lespea** [comment]
@tlimoncelli any update on this?  No code changes are needed just a tag with a higher version number pushed.

**Comment by tlimoncelli** [comment]
Could you send a PR?--
Sent from Gmail Mobile

**Comment by lespea** [comment]
There is no pr you just literally need to apply a new tag to master and push to github...

`git pull && git co master && git tag v1.2.1 && git push --tags`

You should also be able to do it via the github ui here: https://github.com/StackExchange/wmi/tags

Just make sure it's `v1.2.1`

**Comment by tlimoncelli** [comment]
Ah!  you made it very simple and I appreciate it!

```
$ git pull && git co master && git tag v1.2.1 && git push --tags
Already up to date.
Already on 'master'
Your branch is up to date with 'origin/master'.
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To work-github.com:StackExchange/wmi.git
 * [new tag]         v1.2.1 -> v1.2.1
$ 
```

How's it look on your end?

**Comment by lespea** [comment]
Appears to be good... thanks!  I'll just leave this open for a bit until we can validate that gopsutil works now.

**Comment by lespea** [comment]
Everything looks good.  Thanks for the help!
