### ISSUE TITLE
Update go-ole to get fix for Windows on Arm

### ISSUE THREAD

**Issue by acabarbaye** [StackExchange/wmi#68]
Could the version of go-ole be updated to get the fix go-ole/go-ole#224?
And then, could `wmi` be released so that gopsutils can benefit from those fixes?

**Comment by tlimoncelli** [comment]
NOTE: This project is no longer being actively maintained.

We recommend you refer to this fork: https://github.com/yusufpapurcu/wmi

**Comment by acabarbaye** [comment]
@tlimoncelli : I created this PR https://github.com/yusufpapurcu/wmi/pull/1 on the fork you suggested. However, it is not possible to create issues directly on that repository

**Comment by yusufpapurcu** [comment]
I noticed this and I'm trying to track this repo for issues. Actually if anyone has an idea about this problem we can apply this.

**Comment by acabarbaye** [comment]
Hi @yusufpapurcu, 
In order to enable issues on your fork, you can do what is suggested there https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig

In Settings, select the following box
![image](https://user-images.githubusercontent.com/29707928/137795755-54225e48-9fba-45c7-a958-a3871457e29c.png)

**Comment by yusufpapurcu** [comment]
Oh I see it now. Thanks!!

**Comment by acabarbaye** [comment]
It seems to work
